{
 "title": "UMEE mainnet dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "chain_id", "label": "chain_id", "query": { "query": "label_values(chain_id)" } },
   { "name": "instance", "label": "instance", "query": { "query": "label_values(instance)" } },
   { "name": "instance_umee_exporter", "label": "instance_umee_exporter", "query": { "query": "label_values(instance)" } },
   { "name": "instance_tendermint_exporter", "label": "instance_tendermint_exporter", "query": { "query": "label_values(instance)" } }
  ]
 },
 "panels": [
  { "title": "$chain_id overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Block Height",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_height{chain_id=\"$chain_id\", instance=\"$instance_tendermint_exporter\"}"
    }
   ]
  },
  {
   "title": "Avg Block Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_block_interval_seconds_sum{chain_id=\"$chain_id\", instance=\"$instance_tendermint_exporter\"}/tendermint_consensus_block_interval_seconds_count{chain_id=\"$chain_id\", instance=\"$instance_tendermint_exporter\"}"
    }
   ]
  },
  {
   "title": "Total Transactions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_total_txs{chain_id=\"$chain_id\", instance=\"$instance_tendermint_exporter\"}"
    }
   ]
  },
  {
   "title": "Number of Transactions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_num_txs{chain_id=\"$chain_id\", instance=\"$instance_tendermint_exporter\"}"
    }
   ]
  },
  {
   "title": "Consensus Rounds",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_rounds{chain_id=\"$chain_id\", instance=\"$instance_tendermint_exporter\"}"
    }
   ]
  },
  {
   "title": "Validators",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 1 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "tendermint_consensus_validators{chain_id=\"$chain_id\", instance=\"$instance_tendermint_exporter\"}",
     "legendFormat": "Active"
    },
    {
     "expr": "tendermint_consensus_missing_validators{chain_id=\"$chain_id\", instance=\"$instance\"}",
     "legendFormat": "Missing"
    },
    {
     "expr": "tendermint_consensus_byzantine_validators{chain_id=\"$chain_id\", instance=\"$instance\"}",
     "legendFormat": "Double sign"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 8, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tendermint_consensus_num_txs{chain_id=\"$chain_id\", instance=\"$instance_tendermint_exporter\"}",
     "legendFormat": "Transactions"
    }
   ]
  },
  {
   "title": "Bonded Tokens",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_validators_power{chain_id=\"$chain_id\", instance=\"$instance_tendermint_exporter\"}"
    }
   ]
  },
  { "title": "Node Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 }, "repeat": "instance" },
  {
   "title": "Connected Peers",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "tendermint_p2p_peers{chain_id=\"$chain_id\", instance=\"$instance_tendermint_exporter\"}"
    }
   ]
  },
  {
   "title": "Missed Blocks",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 5, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_validator_missed_blocks{chain_id=\"$chain_id\", instance=\"$instance_tendermint_exporter\"}"
    }
   ]
  },
  {
   "title": "Block Height",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 9, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_height{chain_id=\"$chain_id\", instance=\"$instance_tendermint_exporter\"}"
    }
   ]
  },
  {
   "title": "Peggo Synchronization",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 13, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "peggo_sync{instance=\"$instance_umee_exporter\", job=\"node_exporter\", server=\"umee-gravity-wars\"}"
    }
   ]
  },
  {
   "title": "Orchestrator balance",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "UMEE" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "orchestrator_umee_balance{instance=\"$instance_umee_exporter\", job=\"node_exporter\", server=\"umee-gravity-wars\"}"
    }
   ]
  },
  {
   "title": "Orchestrator balance",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ETH" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "orchestrator_eth_balance{instance=\"$instance_umee_exporter\", job=\"node_exporter\", server=\"umee-gravity-wars\"}"
    }
   ]
  },
  {
   "title": "Voting Power",
   "type": "stat",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_validator_power{chain_id=\"$chain_id\", instance=\"$instance_tendermint_exporter\"}"
    }
   ]
  },
  {
   "title": "Latest Block Height (sync)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 9, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_latest_block_height{chain_id=\"$chain_id\", instance=\"$instance_tendermint_exporter\"}"
    }
   ]
  },
  {
   "title": "Umeed version is last",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 13, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "umee_version{instance=\"$instance_umee_exporter\", job=\"node_exporter\", server=\"umee-gravity-wars\"}"
    }
   ]
  },
  {
   "title": "Own ETH Block Height",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "local_eth_block_height{instance=\"$instance_umee_exporter\", job=\"node_exporter\", server=\"umee-gravity-wars\"}"
    }
   ]
  },
  {
   "title": "Last Signed Height",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 9, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_validator_last_signed_height{chain_id=\"$chain_id\", instance=\"$instance_tendermint_exporter\"}"
    }
   ]
  },
  {
   "title": "Peggo version is last",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 13, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "peggo_version{instance=\"$instance_umee_exporter\", job=\"node_exporter\", server=\"umee-gravity-wars\"}"
    }
   ]
  },
  {
   "title": "Infura ETH Block Height",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "eth_block_height{instance=\"$instance_umee_exporter\", job=\"node_exporter\", server=\"umee-gravity-wars\"}"
    }
   ]
  },
  { "title": "Hardware Monitor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 }, "repeat": "instance" },
  {
   "title": "Disk Space Use",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=~\"$instance\", mountpoint=\"/\"} * 100) / node_filesystem_size_bytes{instance=~\"$instance\", mountpoint=\"/\"})",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Free Disk Space",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 19, "x": 5, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{instance=~\"$instance\", mountpoint=\"/\"}",
     "legendFormat": "Free space"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1- sum(increase(node_cpu_seconds_total{mode=\"idle\", instance=~\"$instance\"}[5m])) by (instance)/sum(increase(node_cpu_seconds_total[5m])) by (instance)) * 100"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 19, "x": 5, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(1- sum(increase(node_cpu_seconds_total{mode=\"idle\", instance=~\"$instance\"}[5m])) by (instance)/sum(increase(node_cpu_seconds_total[5m])) by (instance)) * 100",
     "legendFormat": "CPU Load"
    }
   ]
  },
  {
   "title": "RAM Use",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (node_memory_MemTotal_bytes{instance=~\"$instance\"} - node_memory_MemAvailable_bytes{instance=~\"$instance\"}) / node_memory_MemTotal_bytes{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "RAM Use",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 19, "x": 5, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes{instance=~\"$instance\"} - node_memory_MemAvailable_bytes{instance=~\"$instance\"})",
     "legendFormat": "RAM Memory Load"
    }
   ]
  }
 ]
}